### ISSUE TITLE
Upgrading to Python 3 and adding support for pie chart

### ISSUE THREAD

**Issue by shivramp** [gtnx/pandas-highcharts#11]
Hi ,

I downloaded this package and installed it for Python 3.4. it did not work.

I changed core.py module to 
- Work with Python 3
- Made APIs more generic cab called by pandas or non-panda by passing X_LIST and Y_LIST to be plotted as two separate list.
- Added support for 'pie' plot.

Do you want me to submit code to you so that yo can make new version.
If not is it okay to create branch 'yieldfrom-pandas-highchart'  and add changes there ?

Regards,
Shivaram

**Comment by gtnx** [comment]
Hi shivaram
Thanks for contributing. Could you make a pull request?
Thanks

**Comment by shivramp** [comment]
I have emailed you

the modified core.py and a sample usage python program.

**Comment by shivramp** [comment]
Hi Guillaume Thomas,
Attached is the updated core,py

Work with Python 3Made APIs more generic cab called by pandas or non-panda by passing X_LIST and Y_LIST to be plotted as two separate list.Added support for 'pie' plot.
A sample usage / help program :===================================================================#!/usr/local/bin/python3.4

# Note : This Example is run through "ipython nootebook", need to run "ipython nootebook"# using the Python 3 version installed in your machine.

import pandas as pdfrom urllib.request import urlopenfrom IPython.display import display, display_pretty, Javascript, HTMLfrom py_hicharts import serialize

df = pd.read_csv(    urlopen('http://www.quandl.com/api/v1/datasets/ODA/DEU_PCPIPCH.csv?column=1'))

df["Date"] = df["Date"].apply(lambda x: int(x[:4]))df = df.sort("Date")#print(df) ; print ('\n')

x_list = df['Date'].tolist() # If this does not work try df['Date'].get_values().tolist() inp_list = df['Value'].tolist()output_json_dict = {}
output_json_dict = serialize(inp_list, "germany rate",  output_json_dict,  title="Germany inflation rate", x_title="collection year", x_categories=x_list, y_title="Inflation rate", render_to="chart1") 

# This is to show that you can add different y-serieschart = serialize(inp_list, "new germany rate",  output_json_dict, "add_series", "get_new_hichart")

display(HTML("""    <div id="chart1"></div>    <script type="text/javascript">%(chart)s</script>""" % locals())) 

# pie chart examplepie_name_list = ["Firefox", "IE", "Chrome", "Saafari", "Opera", "Others"]pie_value_list = [45, 26.8, 12.8, 8.5, 6.2, 0.7]

output_json_dict={}                  chart = serialize(pie_value_list, "Browsershare",  output_json_dict,                             "get_new_hichart", title="Browsershare", x_title="Browser names",                             x_categories=pie_name_list, y_title="browser use percentage",                             kind="pie",render_to="chart5")

# display(HTML("""    <div id="chart5"></div>    <script type="text/javascript">%(chart)s</script>""" % locals()))

Date: Wed, 4 Mar 2015 15:33:14 -0800

**Comment by shivramp** [comment]
Hi Guillaume.

I am not familiar with pull request, let me know what I need to do.
I have given you all changes I did.

**Comment by gtnx** [comment]
Please read [this about pull requests](https://help.github.com/articles/using-pull-requests). 
I added support for py3.4. If it's ok for you, could you close the issue?

**Comment by gtnx** [comment]
I added support for pie chart. I close the issue
