### ISSUE TITLE
Update IPython notebook example

### ISSUE THREAD

**Issue by garaud** [gtnx/pandas-highcharts#2]
- the `serialize` function raised a JSONEncoder error for your first chart example (data from Quandl)
  (I use pandas 0.15.2 but I don't know if it's related)
- If you convert the string date representation from Quandl data with `pd.read_csv([...], parse_dates=[0])` (suppose "Date" is the first column), your serializer works very well and turns dates into a JSON format that Highchart can understand (you don't have to convert string into a int I guess)
- The first `display(HTML("""[highchart <script>]""")) cell have a`%`  but nothing to replace in the string.
- I wonder why you call `locals()` instead of a dict with a simple key,value with your chart.
- Good job!!

**Comment by garaud** [comment]
I made a Notebook too: a DataFrame with a timeseries as its index. No need to convert dates. It rocks!

Take a look at http://nbviewer.ipython.org/gist/garaud/9dbef25d2f586ec9ec5d

There are also the same data plotted with matplotlib (ggplot style, much better than the default one), seaborn and then highcharts.

**Comment by gtnx** [comment]
- I also used pandas==0.15.2. Could you provide me the backtrace?
- Good to know
- Fixed
- I use locals() because you don't have to create the dict {"foo": foo} which i find useless. It's simple, elegant. 
- Thanks!

**Comment by garaud** [comment]
This must be the same JSONEncoder error as mentioned at #4

**Comment by gtnx** [comment]
Is this problem solved by using the pandas.io.json.dumps function?

**Comment by garaud** [comment]
Yep!!
