### ISSUE TITLE
Sample dataframe

### ISSUE THREAD

**Issue by s-celles** [gtnx/pandas-highcharts#25]
Hello,

maybe you should put in doc a sample DataFrame

with 

```
dat = """ts;A;B;C
2015-01-01 00:00:00;27451873;29956800;113
2015-01-01 01:00:00;20259882;17906600;76
2015-01-01 02:00:00;11592256;12311600;48
2015-01-01 03:00:00;11795562;11750100;50
2015-01-01 04:00:00;9396718;10203900;43
2015-01-01 05:00:00;14902826;14341100;53"""
from pandas.compat import StringIO
df = pd.read_csv(StringIO(dat), sep=';', index_col='ts', parse_dates='ts')
```

or with a random walk

```
N = 600
index = pd.date_range('2015-01-01', periods=N, freq='1D')
df = pd.DataFrame(np.random.randn(N, 3), index=index, columns=list('ABC'))
df = df.cumsum() + 800
```

it will be easier to give pandas-highcharts a try.

Here is a link to show it
http://nbviewer.ipython.org/github/scls19fr/pandas_timeseries_notebooks_samples/blob/master/pandas-highcharts.ipynb

Kind regards

**Comment by gtnx** [comment]
Thanks for the contribution. Why do you say it will be easier to give pandas-highcharts a try?

**Comment by s-celles** [comment]
because user just have to copy paste code from `README.rst` with a sample dataframe and see result.

**Comment by gtnx** [comment]
Oh of course, i thought you were talking of `example.ipynb`
