### ISSUE TITLE
Able to plot DataFrame with timeseries as an Hichstock chart

### ISSUE THREAD

**Issue by garaud** [gtnx/pandas-highcharts#8]
ref: http://www.highcharts.com/stock/demo & http://api.highcharts.com/highstock

**Comment by gtnx** [comment]
Nice feature. Have you started the implementation?

**Comment by garaud** [comment]
Not yet, I tested something in a Notebook but failed... I have to read more about the API of Highcharts.

**Comment by gtnx** [comment]
Can we close this issue?

**Comment by garaud** [comment]
Yes we can. I thought that I wrote à 'closes #8' in a commit message. It's
suppose to automatically close the issue.
Le 5 mars 2015 20:02, "Guillaume Thomas" notifications@github.com a écrit
:
